version: "3"

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - db-data:/var/lib/mysql 

  back:
    build: ./back 
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' " 
    volumes:
      - ./back:/app:cached #ホスト側の./sky-backディレクトリと、コンテナ側のappディレクトリが共有される。
    environment: # 追加
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    stdin_open: true
    tty: true
    depends_on:
      - db #mysqlがrailsに先行して起動する
    ports:
      - 3000:3000  #ホストコンピュータのポート：Docker内のポート

  front:
    build: ./front
    command: yarn run dev
    volumes:
      - ./front:/app:cached
    ports:
      - 8080:3000
      #ホストコンピュータのポート：Docker内のポート
    depends_on:
      - back

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: