version:                     2.1

# 実行するjob
jobs:
  # buildするjob
  build:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:              build continer
          command:           docker-compose build
  # testするjob
  test:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:              start container
          command:           docker-compose up -d
      - run:                 sleep 30
      - run:
          name:              test database creates
          command:           docker-compose run back rails db:create RAILS_ENV=test
      - run:
          name:              test database migrate
          command:           docker-compose run back rails db:migrate RAILS_ENV=test
      - run:
          name:              rspec test
          command:           docker-compose run back bundle exec rspec spec
      - run:
          name:              stop container
          command:           docker-compose down

# 順番を制御するworkflow
workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build