version:                     2.1

orbs:
  aws-ecr:                   circleci/aws-ecr@7.0.0
  aws-ecs:                   circleci/aws-ecs@2.2.1

jobs:
  build:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:              build continer
          command:           docker-compose build
  test:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:              container up
          command:           docker-compose up -d
      - run:                 sleep 30
      - run:
          name:              creates test db
          environment: 
              RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
          command:           docker-compose run back rails db:create RAILS_ENV=test
      - run:
          name:              test database migrate
          command:           docker-compose run back rails db:migrate RAILS_ENV=test
      - run:
          name:              rspec test
          command:           docker-compose run back bundle exec rspec spec
      - run:
          name:              stop container
          command:           docker-compose down

workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
            name:                         'build-and-push-back'
            account-url:                  AWS_ECR_ACCOUNT_URL
            region:                       AWS_REGION
            repo:                         ${REPO_NAME_BACK}
            tag:                          "${CIRCLE_SHA1}" 
            path:                         './back'
            dockerfile:                   Dockerfile
            extra-build-args:             '--build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY'
            requires:
              - test
            filters:
              branches:
                only:
                  - master
      - aws-ecr/build-and-push-image:
            name:                         'build-and-push-front'
            account-url:                  AWS_ECR_ACCOUNT_URL
            region:                       AWS_REGION
            repo:                         ${REPO_NAME_FRONT}
            tag:                          "${CIRCLE_SHA1}"
            path:                         './front'
            dockerfile:                   Dockerfile
            requires:
              - test
            filters:
              branches:
                only:
                  - master