version:                     2.1

orbs:
  aws-ecr:                   circleci/aws-ecr@7.0.0
  aws-ecs:                   circleci/aws-ecs@2.2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name:              building
          command:           docker-compose build 
  test:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:             testing
          command: |      
                            docker-compose up -d
                            sleep 30
                            docker-compose run back rails db:create RAILS_ENV=test
                            docker-compose run back rails db:migrate RAILS_ENV=test
                            docker-compose run back bundle exec rspec spec
                            docker-compose down

workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
            name:                         'build-and-push-back'
            account-url:                  AWS_ECR_ACCOUNT_URL
            region:                       AWS_REGION
            repo:                         ${REPO_NAME_BACK}
            tag:                          "${CIRCLE_SHA1}" 
            path:                         './back'
            dockerfile:                   Dockerfile.pro
            extra-build-args:             '--build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY'
            requires:
              - test
            filters:
              branches:
                only:
                  - master
      - aws-ecr/build-and-push-image:
            name:                         'build-and-push-front'
            account-url:                  AWS_ECR_ACCOUNT_URL
            region:                       AWS_DEFAULT_REGION
            repo:                         ${REPO_NAME_FRONT}
            tag:                          "${CIRCLE_SHA1}"
            path:                         './front'
            dockerfile:                   Dockerfile.pro
            requires:
              - test
            filters:
              branches:
                only:
                  - master
#      - aws-ecs/deploy-service-update:
#            family:                       ${FAMILY_NAME_BACK}
#            cluster-name:                 ${CLUSTER_NAME}
#            aws-region:                   AWS_DEFAULT_REGION
#            container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-back,image-and-tag=${AWS_ECR_ACCOUNT_URL}/${REPO_NAME_BACK}:${CIRCLE_SHA1}'
#            requires:
#              - build-and-push-back
#            filters:
#              branches:
#                only:
#                  - master
#      - aws-ecs/deploy-service-update:
#            family:                       ${FAMILY_NAME_FRONT}
#            service-name:                 ${SERVICE_NAME_FRONT}
#            cluster-name:                 ${CLUSTER_NAME}
#            aws-region:                   ${AWS_REGION}
#            container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-front,image-and-tag=${AWS_ECR_ACCOUNT_URL}/${REPO_NAME_FRONT}:${CIRCLE_SHA1}'
#            requires:
#              - build-and-push-front
#            filters:
#              branches:
#               only:
#                  - master