version: "3"

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - db-data:/var/lib/mysql 

  back:
    build: ./back 
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' " 
    volumes:
      - ./back:/app:cached 
    #environment:
      #RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    stdin_open: true
    tty: true
    depends_on:
      - db 
    ports:
      - 3000:3000 

  front:
    build: ./front
    volumes:
      - ./front:/app:cached 
    command: yarn run dev
    ports:
      - 8000:3000

volumes:
  db-data: